const children=[
    { 
        firstname:'John',
        lastname:'Timothy',
        gender:'male', 
        adopted:'false'
    },
    { 
        firstname:'Silas',
        lastname:'Paul',
        gender:'male',
        adopted:'false'
    },
    { 
        firstname:'Jennie',
        lastname:'John',
        gender:'female',
        adopted:false
    },
    { 
        firstname:'Marvelous',
        lastname:'Henry',
        gender:'male',
        adopted:false
    },
    { 
        firstname:'Chinaza',
        lastname:'Bright',
        gender:'male',
        adopted:false
    },
    { 
        firstname:'Bridget',
        lastname:'Osinachi',
        gender:'female',
        adopted:true
    },
    { 
        firstname:'Norved',
        lastname:'Titus',
        gender:'male',
        adopted:false
    },
    { 
        firstname:'Chioma',
        lastname:'Livinus',
        gender:'female',
        adopted:true
    },
    { 
        firstname:'Sunny',
        lastname:'Chiemela',
        gender:'male',
        adopted:true
    },
    { 
        firstname:'Madonna',
        lastname:'John',
        gender:'male',
        adopted:false
    },
]

export default children
